baseURL: https://moments.jiacheng.site/
languageCode: zh-Hans
theme: moments
paginate: 10
paginatePath: .
params:
  title: Moments of Jiacheng
  signature: 爱好文艺，趣味高雅，精通各种雕虫小技
  name: Jiacheng
  avatar: /avatar.jpg
