baseURL: https://farseash.github.io/demo-hugo-theme-moments/
languageCode: zh-Hans
theme: moments
paginate: 10
paginatePath: .
params:
  title: Moments Demo 112
  signature: 人生如逆旅，我亦是行人aa。
  cover: https://cdn.pixabay.com/photo/2018/03/13/22/53/puzzle-3223941_1280.jpg
  name: Default User
  avatar: /img/default_avatar.png
